name = "getapro-cron"
main = "src/index.ts"
compatibility_date = "2024-10-09"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true
route=""




kv_namespaces = [
  { binding = "GETAPRO_JOBS", id = "bda05ca3c5994d6c906e354b4a5b5a90" }
]


# [observability]
# enabled = true
# head_sampling_rate = 1

[observability]
enabled = true
head_sampling_rate = 1



[triggers]
crons = ["* * * * *"]

