name = "getapro-cron"
main = "src/index.ts"
compatibility_date = "2024-10-09"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true
route=""
# [vars]
# MY_VAR = "my-variable"



# [observability]
# enabled = true
# head_sampling_rate = 1

[triggers]
crons = ["* * * * *"]